services:
  mysql:
    image: mysql:8.4
    container_name: mysql-local
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
      
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
